// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw7FdlCSRHoLzxnlFle8nbx3kBF1Ke2bU',
    appId: '1:553182019068:web:c76652f7f888b8de03c679',
    messagingSenderId: '553182019068',
    projectId: 'iysocial',
    authDomain: 'iysocial.firebaseapp.com',
    storageBucket: 'iysocial.appspot.com',
    measurementId: 'G-N926KPL46X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNAObJ-yhWi_gv-YFoqg-EAR4Jn4WQonU',
    appId: '1:553182019068:android:93c1280b6a35edb503c679',
    messagingSenderId: '553182019068',
    projectId: 'iysocial',
    storageBucket: 'iysocial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBVY3thz9mSwccLbjyFr5y63POqUSTeiI',
    appId: '1:553182019068:ios:3d5190a13c57436c03c679',
    messagingSenderId: '553182019068',
    projectId: 'iysocial',
    storageBucket: 'iysocial.appspot.com',
    iosBundleId: 'com.example.minimalsocialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBVY3thz9mSwccLbjyFr5y63POqUSTeiI',
    appId: '1:553182019068:ios:bec62ead48f3cd2503c679',
    messagingSenderId: '553182019068',
    projectId: 'iysocial',
    storageBucket: 'iysocial.appspot.com',
    iosBundleId: 'com.example.minimalsocialapp.RunnerTests',
  );
}
